host: pbr-example.greatlion.tech
address: ":8080"
modules:
  thegrumpylion/test-pbr:
    remote: github.com
plugins:
  greatliontech/rtk-query:
    image: ghcr.io/greatliontech/protoc-gen-rtk-query:v0.4.7
credentials:
  bsr:
    buf.build: ${BUF_TOKEN}
  git:
    github.com/thegrumpylion/*:
      token: ${GITHUB_TOKEN}
