# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "0.0.0-dev"
  BINARY_NAME: pbr
  BUILD_DIR: ./bin
  MAIN_PKG: ./cmd/pbr
  LDFLAGS: -ldflags "-X main.version={{.VERSION}}"

tasks:
  default:
    desc: Display this help message.
    cmds:
      - task --list
    silent: true

  # Build tasks
  build:
    desc: Build the pbr binary
    cmds:
      - go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PKG}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  build:linux:
    desc: Build for Linux (amd64)
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PKG}}

  build:linux:arm64:
    desc: Build for Linux (arm64)
    env:
      GOOS: linux
      GOARCH: arm64
    cmds:
      - go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-arm64 {{.MAIN_PKG}}

  build:darwin:
    desc: Build for macOS (amd64)
    env:
      GOOS: darwin
      GOARCH: amd64
    cmds:
      - go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PKG}}

  build:darwin:arm64:
    desc: Build for macOS (arm64)
    env:
      GOOS: darwin
      GOARCH: arm64
    cmds:
      - go build {{.LDFLAGS}} -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PKG}}

  build:all:
    desc: Build for all platforms
    deps:
      - build:linux
      - build:linux:arm64
      - build:darwin
      - build:darwin:arm64

  # Test tasks
  test:
    desc: Run all unit tests
    cmds:
      - go test -v ./...

  test:short:
    desc: Run short tests only
    cmds:
      - go test -short ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
    generates:
      - coverage.out
      - coverage.html

  test:coverage:func:
    desc: Show coverage by function
    deps:
      - test:coverage
    cmds:
      - go tool cover -func=coverage.out

  # Lint and format tasks
  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  # Clean tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html

  # Development tasks
  dev:
    desc: Run the server in development mode
    cmds:
      - go run {{.MAIN_PKG}} -config-file ./e2e/config.yaml

  # E2E tests
  e2e:setup:
    desc: Generate e2e certificates
    dir: e2e/certs
    cmds:
      - go run gen.go

  e2e:setup:hosts:
    desc: Add test domain to /etc/hosts (requires sudo)
    cmds:
      - grep -q "pbr-example.greatlion.tech" /etc/hosts || echo '127.0.0.1 pbr-example.greatlion.tech' | sudo tee -a /etc/hosts

  e2e:setup:trust-ca:arch:
    desc: Trust CA certificate (Arch Linux)
    cmds:
      - sudo trust anchor e2e/certs/ca.crt

  e2e:setup:trust-ca:ubuntu:
    desc: Trust CA certificate (Ubuntu/Debian)
    cmds:
      - sudo cp e2e/certs/ca.crt /usr/local/share/ca-certificates/pbr-test-ca.crt
      - sudo update-ca-certificates

  e2e:setup:trust-ca:fedora:
    desc: Trust CA certificate (Fedora/RHEL)
    cmds:
      - sudo cp e2e/certs/ca.crt /etc/pki/ca-trust/source/anchors/pbr-test-ca.crt
      - sudo update-ca-trust

  e2e:setup:trust-ca:macos:
    desc: Trust CA certificate (macOS)
    cmds:
      - sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain e2e/certs/ca.crt

  e2e:setup:all:
    desc: Full e2e setup (certs + hosts + trust CA for Arch)
    cmds:
      - task: e2e:setup
      - task: e2e:setup:hosts
      - task: e2e:setup:trust-ca:arch

  e2e:envoy:
    desc: Start Envoy proxy for e2e tests
    dir: e2e
    cmds:
      - envoy -c envoy.yaml

  e2e:envoy:docker:
    desc: Start Envoy proxy using Docker
    dir: e2e
    cmds:
      - docker run --rm -v $(pwd):/etc/envoy --network host envoyproxy/envoy:v1.28-latest -c /etc/envoy/envoy.yaml

  e2e:check:
    desc: Check e2e prerequisites
    cmds:
      - echo "Checking prerequisites..."
      - which buf || echo "ERROR - buf CLI not found"
      - which envoy || echo "WARNING - envoy not found (can use Docker)"
      - grep -q "pbr-example.greatlion.tech" /etc/hosts && echo "OK - hosts entry exists" || echo "ERROR - run 'task e2e:setup:hosts'"
      - test -f e2e/certs/ca.crt && echo "OK - certificates exist" || echo "ERROR - run 'task e2e:setup'"
      - curl -s --max-time 2 http://127.0.0.1:8080 > /dev/null 2>&1 && echo "OK - PBR server running" || echo "WARNING - PBR server not running"
      - curl -s --max-time 2 https://pbr-example.greatlion.tech > /dev/null 2>&1 && echo "OK - Envoy proxy running" || echo "WARNING - Envoy not running"

  e2e:
    desc: Run e2e tests (requires PBR + Envoy running)
    cmds:
      - go test -v ./e2e/...

  e2e:basic:
    desc: Run basic module e2e tests
    cmds:
      - go test -v ./e2e/... -run TestBasicModule

  e2e:deps:
    desc: Run dependency e2e tests
    cmds:
      - go test -v ./e2e/... -run TestModuleWithDependencies

  e2e:labels:
    desc: Run labels e2e tests
    cmds:
      - go test -v ./e2e/... -run TestLabels

  e2e:commits:
    desc: Run commit operations e2e tests
    cmds:
      - go test -v ./e2e/... -run TestCommitOperations

  e2e:errors:
    desc: Run error cases e2e tests
    cmds:
      - go test -v ./e2e/... -run TestErrorCases

  # Module management tasks
  mod:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  mod:download:
    desc: Download dependencies
    cmds:
      - go mod download

  mod:verify:
    desc: Verify dependencies
    cmds:
      - go mod verify

  # Docker tasks
  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t pbr:{{.VERSION}} .

  # Release tasks
  release:
    desc: Create release artifacts
    cmds:
      - task: clean
      - task: build:all
      - cd {{.BUILD_DIR}} && sha256sum * > checksums.txt

  # CI tasks
  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt
      - task: vet
      - task: test
      - task: build
