apiVersion: v1
kind: Pod
metadata:
  name: pbr
  namespace: pbrtest
  labels:
    app.kubernetes.io/name: pbr
spec:
  containers:
  - image: ghcr.io/greatliontech/pbr:v0.2.10
    imagePullPolicy: IfNotPresent
    name: pbr
    ports:
    - containerPort: 8080
      protocol: TCP
    securityContext:
      privileged: false
      capabilities:
        add: ["SYS_ADMIN"]
    resources:
      limits:
        smarter-devices/fuse: "1"
      requests:
        smarter-devices/fuse: "1"
    volumeMounts:
    - mountPath: /config
      name: config
      readOnly: true
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: config.yaml
        path: config.yaml
      name: pbr-config
    name: config
