apiVersion: v1
kind: ConfigMap
metadata:
  name: pbr-config
data:
  config.yaml: |
    host: pbr.bookingexpress.app
    address: ":8080"
    modules:
      thegrumpylion/test-pbr:
        remote: github.com
    plugins:
      greatliontech/rtk-query:
        image: ghcr.io/greatliontech/protoc-gen-rtk-query
